# Default values for ecamp3.
# Declare configuration values to be passed into the templates.

chartNameOverride: ""
imageTag: "latest"
imagePullSecrets: []
deploymentTime: ""
domain:
deployedVersion: "devel"
versionLinkTemplate: 'https://github.com/ecamp/ecamp3/commit/{version}'
termsOfServiceLinkTemplate: # 'https://ecamp3.ch/{lang}/tos'
newsLink: # 'https://ecamp3.ch/blog'
helpLink: # 'https://ecamp3.ch/faq'

# enable/disable feature across the complete deployment
featureToggle:
  developer: false # enables various tools/features foreseen for development deployments (language switcher, form controls view, performance measurement view, etc.)
  checklist: false # enables checklist feature in frontend

api:
  subpath: "/api"
  image:
    repository: "docker.io/ecamp/ecamp3-api"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose shared default is .Values.imageTag
    tag:
  service:
    type: ClusterIP
    port: 3001
  metrics:
    port: 2019
  replicaCount: 1
  appEnv: prod
  appDebug: "0"
  appSecret: ""
  corsAllowOrigin: "^https://.*?\\.chart-example\\.local$"
  trustedProxies:
    - "::1"
    - "127.0.0.1"
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
  caddyGlobalOptions: ""
  sentryDsn:
  jwt:
    passphrase:
    privateKey:
    publicKey:
  oauth:
    google:
      clientId: '889440431087-ueuhpadf2g7h5ucdke92mvfaf4l779m4.apps.googleusercontent.com'
      clientSecret: 'HNaD1FNO-a1qliacIrIfcGqO'
    pbsmidata:
      clientId: '2a955efdaaac73f665b29ec182cd9a114db01675ced710a464d33d10f58be600'
      clientSecret: '00a23e48bcb776d453b255428ffe810643db7155a9f3d743d7edf52eac400580'
      baseUrl: 'https://pbs.puzzle.ch'
    cevidb:
      clientId: 'raT1QFf6TOQzpn3yVH-My6YLrmsvOrfMhYypxzjPMWk'
      clientSecret: 'fTxMrzjBn3gPGg3eB0bNMmjRqg4ccs3_su7CaTXtljE'
      baseUrl: 'https://cevi.puzzle.ch'
    jubladb:
      clientId: 'WrKABq7GwmC6h1F0W73OGX_fOTHWWXnKXfrPMHOdQWY'
      clientSecret: 'oQ164RDMIAocL6PhmCoeT1Ymcg-7WcOJZdxCnIph5gM'
      baseUrl: 'https://jubla.puzzle.ch'
    # TODO mtte: Add OAuth credentials
    jemkdb:
      clientId: ''
      clientSecret: ''
      baseUrl: 'https://jemk.puzzle.ch'
  resources:
    requests:
      cpu: 10m
      memory: 120Mi

frontend:
  image:
    repository: "docker.io/ecamp/ecamp3-frontend"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose shared default is .Values.imageTag
    tag:
  sentryDsn:
  service:
    type: ClusterIP
    port: 3000
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
  loginInfoTextKey: 'prod'

print:
  subpath: "/print"
  ingress:
    readTimeoutSeconds:
  image:
    repository: "docker.io/ecamp/ecamp3-print"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose shared default is .Values.imageTag
    tag:
  sentryDsn:
  browserWsEndpoint:
  service:
    type: ClusterIP
    port: 3003
  replicaCount: 1
  renderHTMLTimeoutMs:
  renderPDFTimeoutMs:
  resources:
    requests:
      cpu: 10m
      memory: 150Mi

browserless:
  enabled: true
  domain:
  image:
    repository: "docker.io/browserless/chrome"
    pullPolicy: IfNotPresent
    # renovate: datasource=docker depName=browserless/chrome
    tag: "1.61.1-puppeteer-21.4.1"
  service:
    type: ClusterIP
    port: 3000
  maxConcurrentSessions: 1
  connectionTimeout: 30000
  maxQueueLength: 5
  resources:
    requests:
      cpu: 10m
      memory: 200Mi

mail:
  dummyEnabled: true
  # If using a real mail server, the connection uri to send emails to
  dsn: # smtp://myuser:mypass@mymailserver:1025
  # If the dummy mail server is enabled, the domain where the web interface is available
  subpath: "/mail"
  image:
    repository: "docker.io/maildev/maildev"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose shared default is .Values.imageTag
    tag: "latest"
  service:
    type: ClusterIP
    port: 1080
  resources:
    requests:
      cpu: 10m
      memory: 10Mi

# Full configuration: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
postgresql:
  url:
  dropDBOnUninstall: false
  # An uri with privileges to create and drop a database for the application.
  # Can be left empty if the required database specified in postgresql.url already exists.
  adminUrl:
  dbBackupRestoreImage:
    repository: "docker.io/ecamp/ecamp3-db-backup-restore"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose shared default is .Values.imageTag
    tag:
  backup:
    schedule:
    s3:
      endpoint:
      bucket:
      accessKeyId:
      accessKey:
    encryptionKey:
  restore:
    # null => no restore, latest => restore latest backup, s3 key => restore this backup
    sourceFile:
    sourceAppName:
    s3:
      endpoint:
      bucket:
      accessKeyId:
      accessKey:
    inviteSupportAccountToInterestingCamps: false
    encryptionKey:

recaptcha:
  siteKey:
  secret:

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: true
  basicAuth:
    enabled: false
    username:
    password:
  annotations:
    # kubernetes.io/tls-acme: "true"
  className: nginx
  tls:

apiCache:
  enabled: false
  image:
    repository: "docker.io/ecamp/ecamp3-varnish"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose shared default is .Values.imageTag
    tag:
  service:
    type: ClusterIP
    ports:
      http: 3000
      purge: 3001
  varnishSize: 50M
  varnishHttpPort: 8080
  varnishPurgePort: 8081
  sendXKeyHeadersDownstream: false
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
  logging:
    enabled: true
    customOutput: '{ "received_at": "%t", "varnish_side": "%{Varnish:side}x", "method": "%m", "url": "%U", "query": "%q", "response_bytes": %b, "time_taken": %D, "status": %s, "handling": "%{Varnish:handling}x", "response_reason": "%{VSL:RespReason}x", "fetch_error": "%{VSL:FetchError}x" }'
    customOutputJsonFormat: true
    # Timeout before returning error on initial VSM connection.
    # If set the VSM connection is retried every 0.5 seconds for this many seconds.
    # If zero the connection is attempted only once and will fail immediately if unsuccessful.
    # If set to "off", the connection will not fail, allowing the utility to start and wait indefinetely for the Varnish instance to appear.
    # Defaults to "off" in this case.
    timeout: "off"
    resources:
      requests:
        cpu: 10m
        memory: 20Mi
  prometheus:
    enabled: true
    path: "/metrics"
    port: 9131
    resources:
      requests:
        cpu: 10m
        memory: 20Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
