{{- $databaseUrl := .Values.postgresql.url | required ".Values.postgresql.url is required." -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.name" . }}
  labels:
    {{- include "api.selectorLabels" . | nindent 4 }}
    {{- include "app.commonLabels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ $databaseUrl | b64enc | quote }}
  php-app-secret: {{ .Values.api.appSecret | default (randAlphaNum 40) | b64enc | quote }}
  php-jwt-passphrase: {{ .Values.api.jwt.passphrase | default (randAlphaNum 40) | b64enc | quote }}
  jwt-public-key: {{ .Values.api.jwt.publicKey | default "" | b64enc | quote }}
  jwt-private-key: {{ .Values.api.jwt.privateKey | default "" | b64enc | quote }}
  {{- if .Values.api.oauth.google.clientId }}
  oauth-google-client-id: {{ .Values.api.oauth.google.clientId | default "" | b64enc | quote }}
  oauth-google-client-secret: {{ .Values.api.oauth.google.clientSecret | default "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.api.oauth.pbsmidata.clientId }}
  oauth-pbsmidata-client-id: {{ .Values.api.oauth.pbsmidata.clientId | default "" | b64enc | quote }}
  oauth-pbsmidata-client-secret: {{ .Values.api.oauth.pbsmidata.clientSecret | default "" | b64enc | quote }}
  oauth-pbsmidata-base-url: {{ .Values.api.oauth.pbsmidata.baseUrl | default "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.api.oauth.cevidb.clientId }}
  oauth-cevidb-client-id: {{ .Values.api.oauth.cevidb.clientId | default "" | b64enc | quote }}
  oauth-cevidb-client-secret: {{ .Values.api.oauth.cevidb.clientSecret | default "" | b64enc | quote }}
  oauth-cevidb-base-url: {{ .Values.api.oauth.cevidb.baseUrl | default "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.api.oauth.jubladb.clientId }}
  oauth-jubladb-client-id: {{ .Values.api.oauth.jubladb.clientId | default "" | b64enc | quote }}
  oauth-jubladb-client-secret: {{ .Values.api.oauth.jubladb.clientSecret | default "" | b64enc | quote }}
  oauth-jubladb-base-url: {{ .Values.api.oauth.jubladb.baseUrl | default "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.api.oauth.jemkdb.clientId }}
  oauth-jemkdb-client-id: {{ .Values.api.oauth.jemkdb.clientId | default "" | b64enc | quote }}
  oauth-jemkdb-client-secret: {{ .Values.api.oauth.jemkdb.clientSecret | default "" | b64enc | quote }}
  oauth-jemkdb-base-url: {{ .Values.api.oauth.jemkdb.baseUrl | default "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.mail.dummyEnabled }}
  mailer-dsn: {{ .Values.mail.dsn | default (printf "smtp://%s:1025" (include "mail.name" .)) | b64enc | quote }}
  {{- else if .Values.mail.dsn }}
  mailer-dsn: {{ .Values.mail.dsn | b64enc | quote }}
  {{- end }}
  recaptcha-secret: {{ .Values.recaptcha.secret | default "" | b64enc | quote }}
